### ISSUE TITLE
Feature Request:  add Training Cards to "user" column of access log

### ISSUE THREAD

**Issue by mlamparter** [Bucknell-ECE/PortalBox-ManagementPortal#18]
As the site is currently configured, if a training card is authenticated in a Portal box the access log shows a blank entry in the "user" column.  It would be nice if the column instead showed "training card."

**Comment by bu-tegan** [comment]
Similar to issue 17 the user's name is not stored in the log currently only the card_id. While we can get the user's name through the card_id maybe it would be better to keep the name in the log? Of course if a user changes name (marriage/divorce) this may be messy to sort out? It is also messy because trainer cards are not user cards so the data would come from a different table complicating the SQL... I will see what I can do with a case statement though.

**Comment by bu-tegan** [comment]
Added 'Trainer' as user name when card is a recognized training card in commit 1ef97b5ca49c6f9c8569c9b3e23b73bfc9b42678
